train:
	python train_bce.py --path_out experiment1111 --depth=True --augment=True --coord=True --lr=0.000001
	python train_bce.py --path_out experiment1102 --depth=True --augment=True --lr=0.000001
	python train_bce.py --path_out experiment1013 --depth=True --coord=True --lr=0.000001
	python train_bce.py --path_out experiment0114 --augment=True --coord=True --lr=0.000001
	python train_bce.py --path_out experiment1005 --depth=True --lr=0.000001
	python train_bce.py --path_out experiment0016 --coord=True --lr=0.000001
	python train_bce.py --path_out experiment0107 --augment=True --lr=0.000001
