train:
	python train_bce.py --path_out experiment1013 --depth True --augment False --coord True --lr 0.0001
	python train_bce.py --path_out experiment0114 --depth False --augment True --coord True --lr 0.0001
	python train_bce.py --path_out experiment1005 --depth True --augment False --coord False --lr 0.0001
	python train_bce.py --path_out experiment0016 --depth False --augment False --coord True --lr 0.0001
	python train_bce.py --path_out experiment0107 --depth False --augment True --coord False --lr 0.0001
	python train_bce.py --path_out experiment1118 --depth True --augment True --coord True --lr 0.00001
	python train_bce.py --path_out experiment1109 --depth True --augment True --coord False --lr 0.00001
	python train_bce.py --path_out experiment10110 --depth True --augment False --coord True --lr 0.00001
	python train_bce.py --path_out experiment01111 --depth False --augment True --coord True --lr 0.00001
	python train_bce.py --path_out experiment10012 --depth True --augment False --coord False --lr 0.00001
	python train_bce.py --path_out experiment00113 --depth False --augment False --coord True --lr 0.00001
	python train_bce.py --path_out experiment01014 --depth False --augment True --coord False --lr 0.00001
